### PR TITLE
refactor: drop Timestep dict; precompute embeddings_flattened in declared timestep order

### PR DESCRIPTION
**Pull request by felixmaximilian**
Stacked on #229.

## Summary

The `Timestep(TensorDict)` / `TimestepExport` scheme stored positional indices inside a nested dict, and the old packing code had to `sorted(timestep.items(), key=itemgetter(1))` to recover declared order at read time.

This PR collapses that to **one source of truth**: `EpisodeBuilder.timestep` (`tuple[TokenMeta, ...]`). The final design:

- **`projected_embeddings` + `role_embeddings` dropped** from `Episode`/`EpisodeExport` — neither is used downstream of `EpisodeBuilder`. Their sum is stored directly as `embeddings: TensorDict`.
- **`embeddings_flattened: Tensor`** replaces the old `embeddings_unpacked` field — precomputed in `forward()` by packing `embeddings` in declared `timestep` order using `self._timestep_keys`, then stored as a direct field on both `Episode` and `EpisodeExport`.
- **`_timestep_keys`** computed once in `EpisodeBuilder.__init__` and used in `forward()` to drive the pack order. Never stored on the output objects.
- **`logger.warning` guarded** with `not torch.compiler.is_compiling()` — structlog's `_thread.allocate_lock` is not dynamo-traceable; the guard keeps the warning alive in fake-export paths while making strict export safe.
- **`test_torch_export`** fixed to warm the attention mask cache with an eager forward pass before calling `torch.export.export()`, matching the documented usage contract.

## What didn't work

**`timestep_keys` as a field on `Episode`/`EpisodeExport`** — `torch.export.register_dataclass` treats all dataclass fields as dynamic tensor leaves. Passing `timestep_keys` (a Python tuple of strings) through the forward trace caused an `AttrSource` chain that triggered `AttributeError: 'AttrSource' object has no attribute 'is_input'` in `output_graph.py`. Resolved by precomputing `embeddings_flattened` directly in `forward()` so `timestep_keys` never appears on the output objects.

## Regression gates (from #229, already on this branch)

- `test_embeddings_flattened_order` — verifies `embeddings_flattened` packs tokens in declared `timestep` order, not alphabetically.
- `test_index_unpacked_alignment` — verifies `index.parse(flat embeddings_flattened)` recovers per-token embeddings.
- `test_training_step_losses_snapshot` — deterministic forward with sin-based weights; passes before and after.
- `test_torch_export_fake` — covers `episode_builder`, `policy_objective`, and `control_transformer` export paths.

## Test plan
- [x] 60 tests pass (excluding 2 pre-existing `test_torch_export`/`test_onnx_export` failures on MPS unrelated to this PR)

### CODE REVIEW

File: src/rmind/components/episode.py [hunk 1]
```diff
@@ -67,48 +53,20 @@ def parse(self, src: Tensor, dim: int = 1) -> TensorDict:
...
     projected_embeddings: TensorDict
     role_embeddings: TensorDict
     index: Index
-    timestep: Timestep
+    embeddings_unpacked: Tensor
     attention_mask: FactorizedAttentionMask
 
     @property
     def embeddings(self) -> TensorDict:
         return self.projected_embeddings + self.role_embeddings
```
Comment (egorchakov) [inline src/rmind/components/episode.py]: afaict neither `projected_embeddings` nor `role_embeddings` are used anywhere downstream of `EpisodeBuilder`

if so could probably drop them from `Episode` and just keep an `embeddings` attribute (vs property)

cc @koritsky for visibility

File: src/rmind/components/episode.py [hunk 2]
```diff
@@ -67,48 +53,20 @@ def parse(self, src: Tensor, dim: int = 1) -> TensorDict:
...
-
 class Episode(TensorClass["frozen"]):  # ty:ignore[unsupported-base]
     input: TensorDict
     input_tokens: TensorDict
     input_embeddings: TensorDict
     projected_embeddings: TensorDict
     role_embeddings: TensorDict
     index: Index
-    timestep: Timestep
+    embeddings_unpacked: Tensor
```
Comment (egorchakov) [inline src/rmind/components/episode.py]: tbh @sandhawalia @koritsky i never understood why `_unpacked` since it's the output of `einops.pack`

better naming suggestions? `embeddings_flat`?

File: src/rmind/components/episode.py [hunk 3]
```diff
@@ -228,13 +172,22 @@ def forward(self, batch: TensorTree) -> Episode | EpisodeExport:
...
-
-        attention_mask = self._build_attention_mask(index=index, timestep=timestep)
+        attention_mask = self._build_attention_mask(index=index, timestep=self.timestep)
 
         role_embeddings = self._build_role_embeddings(projected_embeddings)
+
+        embeddings_unpacked, _ = pack(
+            [
+                key_get(projected_embeddings, kp)  # ty:ignore[invalid-argument-type]
+                + key_get(role_embeddings, kp)  # ty:ignore[invalid-argument-type]
```
Comment (egorchakov) [inline src/rmind/components/episode.py]: curious: would a tensordict-native version not work here? export etc?

**Review by egorchakov — CHANGES_REQUESTED** [review]

File: src/rmind/components/episode.py (hunk 3 above)
Comment (felixmaximilian) [reply src/rmind/components/episode.py]: Addressed

File: src/rmind/components/episode.py (hunk 1 above)
Comment (felixmaximilian) [reply src/rmind/components/episode.py]: I dropped them.

File: src/rmind/components/episode.py (hunk 2 above)
Comment (felixmaximilian) [reply src/rmind/components/episode.py]: Token_embeddings is the proposal.

**Review by felixmaximilian — COMMENTED** [review]
addressed all comments

File: src/rmind/components/episode.py (hunk 3 above)
Comment (felixmaximilian) [reply src/rmind/components/episode.py]: Tried it — `TensorDict + .get()` works in eager but breaks strict `torch.export`: `filter_non_tensor_data()` calls `hasattr` internally which dynamo can't trace. Kept `tree_map`
   + `key_get` for the export-safe common path in `forward()`.

  That said, `token_embeddings` is now a property derived from `embeddings` + `timestep_keys`, so there's no pack loop in `forward()` at all. For `Episode` (eager path),
  `embeddings` is a `TensorDict` so the property uses native `.get()`. For `EpisodeExport` (export path), `embeddings` is a `TensorTree` (plain dict) so it falls back to `key_get`   + `MappingKey`.

File: src/rmind/components/episode.py (hunk 2 above)
Comment (felixmaximilian) [reply src/rmind/components/episode.py]: I don't like token_embeddings either. I will address a renaming in a follow-up PR. It's likely going to be embeddings_flattened

**Comment by felixmaximilian** [comment]
Ready for final review!

File: src/rmind/components/episode.py [hunk 4]
```diff
@@ -115,42 +75,30 @@ class EpisodeExport:
...
-
-    @property
-    def embeddings_unpacked(self) -> Tensor:
-        embeddings = self.embeddings
-        paths = (
-            (modality, name)
-            for (_token_type, modality, name), _pos in sorted(
-                tree_leaves_with_path(self.timestep), key=itemgetter(1)
-            )
+    def token_embeddings(self) -> Tensor:
```
Comment (koritsky) [inline src/rmind/components/episode.py]: im still leaning towards something more verbose about the shape/functionality of the output tensor. `embeddings_rolled_out`?

File: src/rmind/components/episode.py [hunk 5]
```diff
@@ -115,42 +75,30 @@ class EpisodeExport:
...
+            [
+                key_get(self.embeddings, (MappingKey(k[0]), MappingKey(k[1])))  # ty:ignore[invalid-argument-type]
+                for k in self.timestep_keys
+            ],
+            "b t * d",
         )
-
-        packed, _ = pack([key_get(embeddings, path) for path in paths], "b t * d")
-
         return packed
```
Comment (koritsky) [inline src/rmind/components/episode.py]: no need to create a variable, return straight away

File: tests/test_components.py [hunk 6]
```diff
@@ -107,18 +107,18 @@ def _causal_mask_inputs(device: torch.device) -> tuple[dict, dict]:
...
+        TokenMeta(
+            TokenType.SPECIAL, Modality.SUMMARY, SummaryToken.OBSERVATION_SUMMARY
+        ),
+        TokenMeta(
+            TokenType.SPECIAL, Modality.SUMMARY, SummaryToken.OBSERVATION_HISTORY
+        ),
+        TokenMeta(TokenType.SPECIAL, Modality.FORESIGHT, "future"),
+        TokenMeta(TokenType.ACTION, Modality.CONTINUOUS, "act"),
+        TokenMeta(TokenType.SPECIAL, Modality.SUMMARY, SummaryToken.ACTION_SUMMARY),
+    )
```
Comment (koritsky) [inline tests/test_components.py:122]: just to align with the rest of the codebase convention, "act" -> "action", "obs" -> "observation" ?

File: tests/test_export.py [hunk 7]
```diff
@@ -242,7 +242,9 @@ def test_episode_builder_warms_attention_mask_cache(
 )
 @torch.inference_mode()
 def test_torch_export(module: Module, args: tuple[Any]) -> None:
-    torch.export.export(module.eval(), args=args, strict=True)
+    module = module.eval()
+    module(*args)  # warm internal caches (e.g. attention mask) before export
```
Comment (koritsky) [inline tests/test_export.py:242]: good catch!

**Review by koritsky — APPROVED** [review]
mostly naming issues, otherwise solid refactoring

File: src/rmind/components/episode.py [hunk 8]
```diff
@@ -67,46 +53,20 @@ def parse(self, src: Tensor, dim: int = 1) -> TensorDict:
...
-        embeddings = self.embeddings
-        keys = (
-            (modality, name)
-            for (_token_type, modality, name), _pos in sorted(
-                self.timestep.items(include_nested=True, leaves_only=True),
-                key=itemgetter(1),
-            )
+    def token_embeddings(self) -> Tensor:
+        packed, _ = pack(
+            [self.embeddings.get(k) for k in self.timestep_keys], "b t * d"
```
Comment (egorchakov) [inline src/rmind/components/episode.py]: as discussed: this could be an attribute vs `@property`, which would also imply we no longer need to keep `timestep_keys` as an attribute

also applies to `EpisodeExport` but it will be gone soon

**Review by egorchakov — CHANGES_REQUESTED** [review]

File: src/rmind/components/episode.py (hunk 4 above)
Comment (felixmaximilian) [reply src/rmind/components/episode.py]: Renamed it to embeddings_flattened

File: src/rmind/components/episode.py [hunk 9]
```diff
@@ -175,6 +103,9 @@ def __init__(  # noqa: PLR0913
             special_tokens
         )
         self.timestep: tuple[TokenMeta, ...] = timestep
+        self._timestep_keys: tuple[tuple[str, str], ...] = tuple(
+            (token.modality.value, str(token.name)) for token in timestep
```
Comment (egorchakov) [inline src/rmind/components/episode.py]: `token.name` is a already a `str`

(also in a few other places)

File: tests/test_export.py [hunk 10]
```diff
@@ -85,7 +85,7 @@ def encoder_eval(encoder: Module) -> Module:
 @pytest.fixture
 def policy_embedding(encoder_eval: Module, episode: Episode) -> Tensor:
     return encoder_eval(
-        src=episode.embeddings_unpacked.clone(), mask=episode.attention_mask
+        src=episode.embeddings_flattened.clone(), mask=episode.attention_mask
```
Comment (egorchakov) [inline tests/test_export.py]: alas https://github.com/pytorch/pytorch/issues/44027

we don't clone in `ControlTransformer.*_step`/`forward` though, should we?

**Review by egorchakov — CHANGES_REQUESTED** [review]

File: tests/test_components.py (hunk 6 above)
Comment (felixmaximilian) [reply tests/test_components.py:122]: Done :)

File: src/rmind/components/episode.py (hunk 8 above)
Comment (felixmaximilian) [reply src/rmind/components/episode.py]: It is now an attribute.

File: src/rmind/components/episode.py (hunk 9 above)
Comment (felixmaximilian) [reply src/rmind/components/episode.py]: done.

File: tests/test_export.py (hunk 10 above)
Comment (felixmaximilian) [reply tests/test_export.py]: Good catch on the inconsistency. I looked at the cost: `embeddings_flattened` is `[b, t, 338, 384]` — at production batch size (b=90, bf16) a clone is ~134 MB per forward pass. Cloning consistently across all Episode tensors passed to any module would be expensive and ongoing maintenance.

Instead I added `test_encoder_no_inplace_ops` in `test_components.py` which asserts no encoder submodule has `inplace=True`. If anyone ever adds e.g. `nn.ReLU(inplace=True)` to the encoder, CI catches it before it can corrupt Episode state. With that gate in place, the defensive `.clone()` is removed.

Caveat: the test covers module-level `inplace` flags but not tensor-level in-place ops in `forward()` bodies (e.g. `x.add_()`). Those would show up as correctness failures in the existing export/numerics tests.

Comment (felixmaximilian) [reply tests/test_export.py]: Correction to my previous reply — the 'export/numerics tests would catch this' claim was wrong.

`embeddings_flattened` is write-once-read-once: it's passed to the encoder and never read again downstream (objectives use `episode.embeddings` and `episode.index`, not `embeddings_flattened`). So in-place mutation by the encoder would be invisible to all tests regardless of context.

The `RuntimeError: Inplace update to inference tensor outside InferenceMode` does fire in `test_export.py` because that file builds `episode` inside `torch.inference_mode()` — but that's an accidental guard specific to that fixture path, not a systematic one. `conftest.py`'s shared `episode` fixture and `training_step` both create normal tensors with no such protection.

What we're actually relying on: `test_encoder_no_inplace_ops` catches module-level `inplace=True` flags (e.g. `nn.ReLU(inplace=True)`), and since `embeddings_flattened` is never read after the encoder call, even undetected tensor-level in-place ops have no observable effect on correctness today. The risk is purely a future one — if someone adds code that reads `embeddings_flattened` after the encoder.

**Review by egorchakov — APPROVED** [review]

**Comment by felixmaximilian** [comment]
**Phantom merge.** The merge commit was force-rewound from `main` shortly after this PR was marked merged; the changes are no longer reachable from `main`. GitHub doesn't let merged PRs be reopened, so the same branch is re-merged via #242. Closing this in favor of that one.
